#!/usr/bin/env bash

set -euo pipefail

if [[ ! -e puzzle/.check ]]; then
    echo "No hashes file."
    exit 2
fi

readarray -t secrets < <(cat .secret-*)
readarray -t hashes < puzzle/.check

ids=(${secrets[@]%%:*})

i=0
while [[ "$i" -lt "${#hashes[@]}" ]]; do
    if [[ "$i" -lt "${#ids[@]}" ]]; then
        check=$(shasum <<< "${ids[$i]}" | cut -c -40)
        if [[ "${hashes[$i]}" = "$check" ]]; then
            echo "✅ Clue number $i (${ids[$i]})"
        else
            echo "❌ Clue number $i (${ids[$i]})"
        fi
    else
        echo "${hashes[$i]} - SECRET NOT FOUND"
    fi
    i=$((i + 1))
done
